add_rules("mode.debug", "mode.release")

target("stonelog")
    set_kind("binary")
    add_files("src/*.cpp")
    add_includedirs("include")
    set_languages( "c++17")
    
target("AsyncLog")
    set_kind("binary")
    add_files("test/testAsyncLog.cpp")
    add_includedirs("include")
    add_files("src/*.cpp")
    set_languages( "c++17")
    
target("SyncLog")
    set_kind("binary")
    add_files("test/testSyncLog.cpp")
    add_includedirs("include")
    add_files("src/*.cpp")
    set_languages( "c++17")

target("SyncTcp")
    set_kind("binary")
    add_files("test/testSyncTcpLog.cpp")
    add_includedirs("include")
    add_files("src/*.cpp")
    set_languages( "c++17")

target("SyncUdp")
    set_kind("binary")
    add_files("test/testSyncUdpLog.cpp")
    add_includedirs("include")
    add_files("src/*.cpp")
    set_languages( "c++17")

target("AsyncTcp")
    set_kind("binary")
    add_files("test/testAsyncTcpLog.cpp")
    add_includedirs("include")
    add_files("src/*.cpp")
    set_languages( "c++17")

target("AsyncUdp")
    set_kind("binary")
    add_files("test/testAsyncUdpLog.cpp")
    add_includedirs("include")
    add_files("src/*.cpp")
    set_languages( "c++17")
    

